drop table intechordersystem.ACT_GE_PROPERTY cascade;
drop table intechordersystem.ACT_RU_VARIABLE cascade;
drop table intechordersystem.ACT_RU_IDENTITYLINK cascade;
drop table intechordersystem.ACT_RU_TASK cascade;
drop table intechordersystem.ACT_RE_PROCDEF cascade;
drop table intechordersystem.ACT_RU_EXECUTION cascade;
drop table intechordersystem.ACT_ID_MEMBERSHIP cascade;
drop table intechordersystem.ACT_ID_GROUP cascade;
drop table intechordersystem.ACT_ID_USER cascade;
drop table intechordersystem.ACT_ID_INFO cascade;
drop table intechordersystem.ACT_RU_JOB cascade;
drop table intechordersystem.ACT_HI_PROCINST cascade;
drop table intechordersystem.ACT_HI_ACTINST cascade;
drop table intechordersystem.ACT_HI_TASKINST cascade;
drop table intechordersystem.ACT_HI_DETAIL cascade;
drop table intechordersystem.ACT_HI_COMMENT cascade;
drop table intechordersystem.ACT_HI_ATTACHMENT cascade;
drop table intechordersystem.ACT_RU_EVENT_SUBSCR cascade;
drop table intechordersystem.ACT_EVENT_LOG cascade;
DROP TABLE `intechordersystem`.`ACT_HI_IDENTITYLINK`, `intechordersystem`.`ACT_HI_VARINST`, `intechordersystem`.`ACT_PROCDEF_INFO`;
DROP TABLE `intechordersystem`.`ACT_RE_MODEL`, `intechordersystem`.`ACT_RE_PROCDEF`, `intechordersystem`.`ACT_RU_EXECUTION`;
drop table intechordersystem.ACT_GE_BYTEARRAY cascade;
drop table intechordersystem.ACT_RE_DEPLOYMENT cascade;