spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intechOrderSystem
    username: root
    password: R0botic$1
  jpa:
    show-sql: true #dev
    hibernate:
      ddl-auto: update #dev
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jersey:
    application-path: /api
logging:
  file: logs/dev_app.log
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 9000
purchase-order-service:
  sSERVER_UPLOAD_LOCATION_FOLDER: fileUploads
