spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intechOrderSystem
    username: root
    password: p@ssw0rd
    testWhileIdle: true #production
    validationQuery: SELECT 1 #production
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jersey:
      application-path: /api
logging:
  file: logs/dev_app.log #based on env
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 9000
com.intechsouthwest.ordermanagementsystem.services:
  purchaseorder:
    SERVER_UPLOAD_LOCATION_FOLDER: fileUploads
#actuator endpoints disable all but the following
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-endpoints
# http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-use-actuator-with-jersey
endpoints:
  enabled: false
  info:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true
processEngineConfiguration:
  historyLevel: full