spring:
  datasource:
    url: jdbc:mysql://localhost:3306/intechOrderSystem
    username: root
    password: p@ssw0rd
    testWhileIdle: true #production
    validationQuery: SELECT 1 #production
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jersey:
      application-path: /api
logging:
  file: logs/dev_app.log #based on env
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
server:
  port: 9000
services:
  purchaseorder:
    SERVER_UPLOAD_LOCATION_FOLDER: fileUploads